# Python summary part 3

## Error handling

- syntax error 
- runtime error
- logical errors

syntax error

In [1]:
prin("linear regression is a supervised learning algorithm")

NameError: name 'prin' is not defined

In [2]:
print("linear regression is a supervised learning algorithm")

linear regression is a supervised learning algorithm


runtime error

In [3]:
numbers = list(range(5))
numbers

[0, 1, 2, 3, 4]

In [4]:
numbers[10]

IndexError: list index out of range

logical error

In [6]:
import numpy as np 

radius = 5 
area_circle = np.pi*radius

# error: area = pi*radius**2
area_circle


15.707963267948966

try-except

In [8]:
age = float(input("Give me your age"))
age

ValueError: could not convert string to float: 'hello'

In [9]:
try:
    age = float(input("Give me your age"))
except ValueError as err: 
    print(err)

age

could not convert string to float: 'fiftyfive'


53.0

In [12]:
while True:
    try:
        age = float(input("Give me your age"))
        if not 0 <= age <= 125:
            raise ValueError("Year must be between 0 and 125")
        print(f"You are {age} years old")
        break
    except ValueError as err: 
        print(err)



Year must be between 0 and 125
Year must be between 0 and 125
could not convert string to float: 'kfosekf'
You are 12.0 years old


## Functions

```
def name(param1, param2, ...): 
    statements
    ...

name(arg1, arg2, ...)
```

In [13]:
# x is input parameter
def squarer(x):
    return x**2 # return statement

squarer(3) # 3 is an argument


9

In [14]:
squares = [squarer(i) for i in range(10)]
squares

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

default value

In [16]:
def draw_ascii(number_rows=5):
    for i in range(1, number_rows + 1):
        print(i * "x " + (number_rows - i) * "o ")


draw_ascii()

x o o o o 
x x o o o 
x x x o o 
x x x x o 
x x x x x 


In [18]:
draw_ascii(7)

x o o o o o o 
x x o o o o o 
x x x o o o o 
x x x x o o o 
x x x x x o o 
x x x x x x o 
x x x x x x x 


In [19]:
draw_ascii(number_rows=3)

x o o 
x x o 
x x x 


arbitrary arguments, *args

In [21]:
def mean_(*args):
    sum_ = 0
    print(args) # args is a tuple
    # for arg in args:

mean_(1,2,34)

(1, 2, 34)


In [22]:
def mean_(*args):
    sum_ = 0
    for arg in args:
        sum_ += arg
    return sum_/len(args)

mean_(1,2,34)

12.333333333333334

In [23]:

mean_(1,2,3)

2.0

keyword arguments, **kwargs

In [24]:
import numpy as np


def simulate_dices(throws=1, dices=2):
    print(np.random.randint(1, 7, size=(throws, dices)))

# default arguments
simulate_dices()

[[6 4]]


In [25]:
simulate_dices(1,4)

[[5 1 1 6]]


In [26]:
simulate_dices(3,4)

[[4 3 4 6]
 [2 3 3 6]
 [3 5 5 4]]


In [27]:
simulate_dices(throws=5)

[[4 5]
 [6 6]
 [2 3]
 [5 2]
 [6 4]]


In [29]:
simulate_dices(dices=3)

[[5 3 2]]


In [30]:
simulate_dices(dices=5, throws=3)

[[1 4 2 5 6]
 [2 2 6 6 5]
 [1 6 3 2 1]]


In [32]:
options = {"dices":3, "throws":3}

simulate_dices(**options)

[[5 4 2]
 [5 6 4]
 [5 2 2]]


In [33]:
option_list = [1,5]

simulate_dices(*option_list)

[[3 5 3 4 6]]


lambda functions

In [35]:
# def f(x): 
#   return x**3
f = lambda x: x**3 
f(3)

27

In [38]:
students = [("Bob", 92), ("Charlie", 78), ("David", 95), ("Alice", 85)]
students

[('Bob', 92), ('Charlie', 78), ('David', 95), ('Alice', 85)]

In [39]:
sorted(students)

[('Alice', 85), ('Bob', 92), ('Charlie', 78), ('David', 95)]

In [41]:
sorted(students, key = lambda student: student[1], reverse=True)

[('David', 95), ('Bob', 92), ('Alice', 85), ('Charlie', 78)]

## Matplotlib

## Numpy

## File handling

## Datetime